target 'RichQuantify' do
platform :ios, '8.0'
pod 'SDWebImage', '~> 4.0'
pod 'SDAutoLayout', '~> 2.1.7'
pod 'CustomIOSAlertView', '~> 0.9.5'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'DXPopover', '~> 0.1.1'
pod 'AFNetworking', '~> 3.1.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'MJRefresh'
pod 'SDCycleScrollView','~> 1.64'
pod 'IQKeyboardManager'
pod 'SDAutoLayout', '~> 2.1.7'
pod 'Masonry'
pod 'FMDB'
pod 'JRDB'
pod 'SocketRocket'
end
